package com.huseyinkiran.kitchenapp.domain.model

import com.huseyinkiran.kitchenapp.data.remote.model.MealDetailDto

data class MealDetailUIModel(
    val idMeal: String,
    val strMeal: String,
    val strCategory: String,
    val strArea: String,
    val strInstructions: String,
    val strMealThumb: String,
    val strTags: String,
    val strYoutube: String,
    val strSource: Any,
    var isFavorite: Boolean,
    val strIngredient1: String,
    val strIngredient2: String,
    val strIngredient3: String,
    val strIngredient4: String,
    val strIngredient5: String,
    val strIngredient6: String,
    val strIngredient7: String,
    val strIngredient8: String,
    val strIngredient9: String,
    val strIngredient10: String,
    val strIngredient11: String,
    val strIngredient12: String,
    val strIngredient13: String,
    val strIngredient14: String,
    val strIngredient15: String,
    val strIngredient16: Any,
    val strIngredient17: Any,
    val strIngredient18: Any,
    val strIngredient19: Any,
    val strIngredient20: Any,
    val strMeasure1: String,
    val strMeasure2: String,
    val strMeasure3: String,
    val strMeasure4: String,
    val strMeasure5: String,
    val strMeasure6: String,
    val strMeasure7: String,
    val strMeasure8: String,
    val strMeasure9: String,
    val strMeasure10: String,
    val strMeasure11: String,
    val strMeasure12: String,
    val strMeasure13: String,
    val strMeasure14: String,
    val strMeasure15: String,
    val strMeasure16: Any,
    val strMeasure17: Any,
    val strMeasure18: Any,
    val strMeasure19: Any,
    val strMeasure20: Any
)

fun MealDetailDto.toUI(): MealDetailUIModel {
    return MealDetailUIModel(
        idMeal = idMeal.orEmpty(),
        strMeal = strMeal.orEmpty(),
        strCategory = strCategory.orEmpty(),
        strArea = strArea.orEmpty(),
        strInstructions = strInstructions.orEmpty(),
        strMealThumb = strMealThumb.orEmpty(),
        strTags = strTags.orEmpty(),
        strYoutube = strYoutube.orEmpty(),
        strSource = strSource?.toString() ?: "",
        isFavorite = false,
        strIngredient1 = strIngredient1.orEmpty(),
        strIngredient2 = strIngredient2.orEmpty(),
        strIngredient3 = strIngredient3.orEmpty(),
        strIngredient4 = strIngredient4.orEmpty(),
        strIngredient5 = strIngredient5.orEmpty(),
        strIngredient6 = strIngredient6.orEmpty(),
        strIngredient7 = strIngredient7.orEmpty(),
        strIngredient8 = strIngredient8.orEmpty(),
        strIngredient9 = strIngredient9.orEmpty(),
        strIngredient10 = strIngredient10.orEmpty(),
        strIngredient11 = strIngredient11.orEmpty(),
        strIngredient12 = strIngredient12.orEmpty(),
        strIngredient13 = strIngredient13.orEmpty(),
        strIngredient14 = strIngredient14.orEmpty(),
        strIngredient15 = strIngredient15.orEmpty(),
        strIngredient16 = strIngredient16?.toString() ?: "",
        strIngredient17 = strIngredient17?.toString() ?: "",
        strIngredient18 = strIngredient18?.toString() ?: "",
        strIngredient19 = strIngredient19?.toString() ?: "",
        strIngredient20 = strIngredient20?.toString() ?: "",
        strMeasure1 = strMeasure1.orEmpty(),
        strMeasure2 = strMeasure2.orEmpty(),
        strMeasure3 = strMeasure3.orEmpty(),
        strMeasure4 = strMeasure4.orEmpty(),
        strMeasure5 = strMeasure5.orEmpty(),
        strMeasure6 = strMeasure6.orEmpty(),
        strMeasure7 = strMeasure7.orEmpty(),
        strMeasure8 = strMeasure8.orEmpty(),
        strMeasure9 = strMeasure9.orEmpty(),
        strMeasure10 = strMeasure10.orEmpty(),
        strMeasure11 = strMeasure11.orEmpty(),
        strMeasure12 = strMeasure12.orEmpty(),
        strMeasure13 = strMeasure13.orEmpty(),
        strMeasure14 = strMeasure14.orEmpty(),
        strMeasure15 = strMeasure15.orEmpty(),
        strMeasure16 = strMeasure16?.toString() ?: "",
        strMeasure17 = strMeasure17?.toString() ?: "",
        strMeasure18 = strMeasure18?.toString() ?: "",
        strMeasure19 = strMeasure19?.toString() ?: "",
        strMeasure20 = strMeasure20?.toString() ?: ""
    )
}

fun MealDetailUIModel.toMeal(): MealUIModel {
    return MealUIModel(
        idMeal = idMeal,
        strMeal = strMeal,
        strMealThumb = strMealThumb,
        isFavorite = false
    )
}
